package app.calculator;

public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public calculator() {

        initComponents();
        jButton1.setMnemonic(java.awt.event.KeyEvent.VK_1);
        jButton2.setMnemonic(java.awt.event.KeyEvent.VK_2);
        jButton3.setMnemonic(java.awt.event.KeyEvent.VK_3);
        jButton4.setMnemonic(java.awt.event.KeyEvent.VK_4);
        jButton5.setMnemonic(java.awt.event.KeyEvent.VK_C);
        jToggleButton1.setMnemonic(java.awt.event.KeyEvent.VK_ENTER);
        jButton5.setOpaque(false);//
        jButton5.setContentAreaFilled(false);
        jTextField1.grabFocus();
        jTextField3.setEditable(false);
        History.run();

    }

    private boolean ifEmpty() {
        if (jTextField1.getText().equals("")) {
            jTextField3.setText("Please complete the equation");
            History.addInfo("Wrong Equation.");
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        jLabel1.setText("Calculator");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setColumns(20);

        jTextField2.setColumns(20);

        jTextField3.setColumns(20);

        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("*");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("/");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("number1");

        jLabel3.setText("number2");

        jLabel4.setText("result");

        jToggleButton1.setText("History");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addGap(139, 139, 139))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(69, 69, 69)
                                                        .addComponent(jToggleButton1))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jButton2)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jButton3)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jButton4))
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel1)
                                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(21, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton1)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3)
                                        .addComponent(jButton4))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(17, 17, 17)
                                .addComponent(jButton5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        History.on(jToggleButton1.isSelected());
        if (jTextField1.getText().equals("")) {
            jTextField1.grabFocus();
        } else {
            jTextField2.grabFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField1.grabFocus();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        float n1, n2, r1;
        if (jTextField1.getText().equals("")) {
            jTextField3.setText("Please complete the equation");
            History.addInfo("Wrong Equation.");
        } else {
            if (jTextField2.getText().equals("")) {
                n1 = Float.parseFloat(jTextField1.getText());
                r1 = n1 / tempt;
                jTextField2.grabFocus();
                History.addInfo(n1 + " / " + tempt + " = " + r1);
            } else {
                n1 = Float.parseFloat(jTextField1.getText());
                n2 = Float.parseFloat(jTextField2.getText());
                r1 = n1 / n2;
                tempt = n2;
                jTextField2.grabFocus();
                History.addInfo(n1 + " + " + n2 + " = " + r1);
            }
            jTextField3.setText(String.valueOf(r1));
            jTextField1.setText(String.valueOf(r1));
            jTextField2.setText("");    // TODO add your handling code here:
        }//GEN-LAST:event_jButton4ActionPerformed
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        float n1, n2, r1;
        if (jTextField1.getText().equals("")) {
            jTextField3.setText("Please complete the equation");
            History.addInfo("Wrong Equation.");
        } else {
            if (jTextField2.getText().equals("")) {
                n1 = Float.parseFloat(jTextField1.getText());
                r1 = n1 * tempt;
                jTextField2.grabFocus();
                History.addInfo(n1 + " * " + tempt + " = " + r1);
            } else {
                n1 = Float.parseFloat(jTextField1.getText());
                n2 = Float.parseFloat(jTextField2.getText());
                r1 = n1 * n2;
                tempt = n2;
                jTextField2.grabFocus();
                History.addInfo(n1 + " + " + n2 + " = " + r1);
            }
            jTextField3.setText(String.valueOf(r1));
            jTextField1.setText(String.valueOf(r1));
            jTextField2.setText("");
        }//GEN-LAST:event_jButton3ActionPerformed
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        float n1, n2, r1;
        if (jTextField1.getText().equals("")) {
            jTextField3.setText("Please complete the equation");
            History.addInfo("Wrong Equation.");
        } else {
            if (jTextField2.getText().equals("")) {
                n1 = Float.parseFloat(jTextField1.getText());
                r1 = n1 - tempt;
                jTextField2.grabFocus();
                History.addInfo(n1 + " - " + tempt + " = " + r1);
            } else {
                n1 = Float.parseFloat(jTextField1.getText());
                n2 = Float.parseFloat(jTextField2.getText());
                r1 = n1 - n2;
                tempt = n2;
                jTextField2.grabFocus();
                History.addInfo(n1 + " + " + n2 + " = " + r1);
            }
            jTextField3.setText(String.valueOf(r1));
            jTextField1.setText(String.valueOf(r1));
            jTextField2.setText("");
        }//GEN-LAST:event_jButton2ActionPerformed
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //while (true) {
        float n1, n2, r1;
        if (!ifEmpty()) {
            if (jTextField2.getText().equals("")) {
                n1 = Float.parseFloat(jTextField1.getText());
                r1 = n1 + tempt;
                jTextField2.grabFocus();
                History.addInfo(n1 + " + " + tempt + " = " + r1);
            } else {
                n1 = Float.parseFloat(jTextField1.getText());
                n2 = Float.parseFloat(jTextField2.getText());
                r1 = n1 + n2;
                tempt = n2;
                jTextField2.grabFocus();
                History.addInfo(n1 + " + " + n2 + " = " + r1);
            }

            jTextField3.setText(String.valueOf(r1));
            jTextField1.setText(String.valueOf(r1));
            jTextField2.setText("");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    float tempt = 0;


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);

            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
